# 1. Dependencies#

In [3]:
# gym stuff
import gymnasium as gym
from gymnasium import Env
from gymnasium.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

# helper
import os
import numpy as np
import random

# stable baselines3 stuff
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Types of Space

In [38]:
# Discrete(): Invoking this create th ACTION_SPACE 
# from 0 to 2 descision
actionSpaces = Discrete(3)

In [28]:
#Creating box
box = Box(0,1,shape=(3,3))

In [29]:
box.sample()

array([[0.21002984, 0.88315535, 0.48412606],
       [0.93003005, 0.9716447 , 0.02538518],
       [0.61330354, 0.62346697, 0.10115568]], dtype=float32)

In [45]:
# Tuple
tuple = Tuple((actionSpaces, box))
tuple.sample()

(0,
 array([[0.77726066, 0.10319824, 0.23602076],
        [0.61056846, 0.27630007, 0.9005226 ],
        [0.52653867, 0.07611253, 0.3097697 ]], dtype=float32))

In [74]:
Tuple((actionSpaces, box, Box(0,3,shape=(1,)))).sample()

(0,
 array([[0.16486232, 0.9671017 , 0.93417126],
        [0.4632621 , 0.9804114 , 0.9256742 ],
        [0.75942975, 0.20578282, 0.03242498]], dtype=float32),
 array([2.754945], dtype=float32))

In [51]:
#Dict
dict = Dict({'braking':Discrete(2), 'speed':Box(0,100, shape=(1,))})
dict.sample()

OrderedDict([('braking', 1), ('speed', array([40.241207], dtype=float32))])

In [68]:
Dict({'braking':Discrete(2), 'speed':Box(0,100, shape=(1,)), 'accelerate':Discrete(2)}).sample()

OrderedDict([('accelerate', 1),
             ('braking', 1),
             ('speed', array([63.21558], dtype=float32))])

In [64]:
#MultiBinary
MultiBinary(4).sample()

array([1, 1, 0, 0], dtype=int8)

In [65]:
MultiBinary(2).sample()

array([1, 1], dtype=int8)

In [61]:
#MultiDiscrete 
MultiDiscrete([3, 2, 1]).sample() # see the range randomization

array([1, 0, 0])

In [62]:
MultiDiscrete([4,3,1,4]).sample()

array([2, 0, 0, 0])

# 3. Building an environment

# 4. Test Environment

 # 5. Train Environment

# 6. Save Model